"""NSE/BSE index constituents for the stock-picker menus.

Static snapshots (symbol, company name) — index composition changes over time
via periodic index reconstitution, so treat this as approximate and update
occasionally rather than trusting it as a live feed.
"""
from __future__ import annotations

NIFTY50 = [
    ("RELIANCE", "Reliance Industries"),
    ("TCS", "Tata Consultancy Services"),
    ("HDFCBANK", "HDFC Bank"),
    ("ICICIBANK", "ICICI Bank"),
    ("INFY", "Infosys"),
    ("HINDUNILVR", "Hindustan Unilever"),
    ("ITC", "ITC"),
    ("SBIN", "State Bank of India"),
    ("BHARTIARTL", "Bharti Airtel"),
    ("BAJFINANCE", "Bajaj Finance"),
    ("KOTAKBANK", "Kotak Mahindra Bank"),
    ("LT", "Larsen & Toubro"),
    ("HCLTECH", "HCL Technologies"),
    ("ASIANPAINT", "Asian Paints"),
    ("AXISBANK", "Axis Bank"),
    ("MARUTI", "Maruti Suzuki"),
    ("SUNPHARMA", "Sun Pharmaceutical"),
    ("TITAN", "Titan Company"),
    ("ULTRACEMCO", "UltraTech Cement"),
    ("NESTLEIND", "Nestle India"),
    ("WIPRO", "Wipro"),
    ("ADANIENT", "Adani Enterprises"),
    ("ADANIPORTS", "Adani Ports & SEZ"),
    ("ONGC", "Oil & Natural Gas Corp"),
    ("NTPC", "NTPC"),
    ("POWERGRID", "Power Grid Corp"),
    ("M&M", "Mahindra & Mahindra"),
    ("TATAMOTORS", "Tata Motors"),
    ("TATASTEEL", "Tata Steel"),
    ("JSWSTEEL", "JSW Steel"),
    ("INDUSINDBK", "IndusInd Bank"),
    ("BAJAJFINSV", "Bajaj Finserv"),
    ("BAJAJ-AUTO", "Bajaj Auto"),
    ("HDFCLIFE", "HDFC Life Insurance"),
    ("SBILIFE", "SBI Life Insurance"),
    ("DRREDDY", "Dr. Reddy's Labs"),
    ("CIPLA", "Cipla"),
    ("DIVISLAB", "Divi's Laboratories"),
    ("EICHERMOT", "Eicher Motors"),
    ("GRASIM", "Grasim Industries"),
    ("HEROMOTOCO", "Hero MotoCorp"),
    ("BRITANNIA", "Britannia Industries"),
    ("COALINDIA", "Coal India"),
    ("BPCL", "Bharat Petroleum"),
    ("HINDALCO", "Hindalco Industries"),
    ("TECHM", "Tech Mahindra"),
    ("UPL", "UPL"),
    ("APOLLOHOSP", "Apollo Hospitals"),
    ("LTIM", "LTIMindtree"),
    ("SHRIRAMFIN", "Shriram Finance"),
    ("TATACONSUM", "Tata Consumer Products"),
]

SENSEX30 = [
    ("RELIANCE", "Reliance Industries"),
    ("TCS", "Tata Consultancy Services"),
    ("HDFCBANK", "HDFC Bank"),
    ("ICICIBANK", "ICICI Bank"),
    ("INFY", "Infosys"),
    ("HINDUNILVR", "Hindustan Unilever"),
    ("ITC", "ITC"),
    ("SBIN", "State Bank of India"),
    ("BHARTIARTL", "Bharti Airtel"),
    ("KOTAKBANK", "Kotak Mahindra Bank"),
    ("LT", "Larsen & Toubro"),
    ("BAJFINANCE", "Bajaj Finance"),
    ("HCLTECH", "HCL Technologies"),
    ("ASIANPAINT", "Asian Paints"),
    ("AXISBANK", "Axis Bank"),
    ("MARUTI", "Maruti Suzuki"),
    ("SUNPHARMA", "Sun Pharmaceutical"),
    ("TITAN", "Titan Company"),
    ("ULTRACEMCO", "UltraTech Cement"),
    ("NESTLEIND", "Nestle India"),
    ("M&M", "Mahindra & Mahindra"),
    ("TATAMOTORS", "Tata Motors"),
    ("TATASTEEL", "Tata Steel"),
    ("JSWSTEEL", "JSW Steel"),
    ("INDUSINDBK", "IndusInd Bank"),
    ("POWERGRID", "Power Grid Corp"),
    ("NTPC", "NTPC"),
    ("TECHM", "Tech Mahindra"),
    ("HINDALCO", "Hindalco Industries"),
    ("BAJAJFINSV", "Bajaj Finserv"),
]


def yahoo_symbol(nse_symbol: str) -> str:
    """NSE-listed tickers resolve on Yahoo Finance with a .NS suffix."""
    return f"{nse_symbol}.NS"
